services:
  spring:
    image: auth-v2:1.0
    container_name: con-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: con_rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      
      SPRING_DATASOURCE_URL: jdbc:postgresql://con_db_auth:5432/authentication_data_base
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: 1234
      API_SECURITY_TOKEN_SECRET: my-secret-key
    depends_on:
      - db_auth
    networks:
      - auth_network

  db_auth:
    image: postgres
    container_name: con_db_auth
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authentication_data_base
    volumes:
      - app_data_auth:/var/lib/postgresql/data
    networks:
      - auth_network

  app_rabbitmq:
    image: rabbitmq:management
    container_name: con_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - auth_network

volumes:
  app_data_auth:

networks:
  auth_network:
    driver: bridge
